[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin"
    Permissions-Policy = '''
    geolocation=(self), 
    microphone=()'''
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
[[redirects]]
  from = "/.functions/*"
  to = "/api-migration/:splat"
  status = 200
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ethers","axios","@across-protocol/sdk-v2","@across-protocol/contracts-v2","@ethersproject/providers","@uma/contracts-node","@google-cloud/logging"]
  included_files = ["src/data/*.json"]
