name: Lighthouse CI
on:
  deployment_status:
jobs:
  lighthouseci:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && !contains(github.event.deployment_status.target_url, 'goerli')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: '${{github.event.deployment_status.target_url}}/,${{github.event.deployment_status.target_url}}/airdrop,${{github.event.deployment_status.target_url}}/rewards'
        device: all
        gitHubAccessToken: ${{secrets.GITHUB_TOKEN}}
        prCommentEnabled: true
        wait: true
